package com.griddynamics.rpg.model.arena;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum LocationInfo {
    KAHOLM("Kaholm", "A village inside a glacial river valley with open water to the sea."),
    LINGCOMBE("Lingcombe", "A bridge at the head of a deep river valley."),
    TOCKTHORP("Tockthorp", "A farm"),
    BRERBURY("Brerbury", "A picturesque town"),
    EPPISTANMILL("Eppistan Mill", "An old industrial building converted into apartments along the sea front."),
    SHUNSTWICKDRIVE("Shunstwick Drive", "Shunstwick DriveA cut through from one part of town to another in a rough area."),
    ARAHAMPCOTEHOUSE("Arahampcote House", "The newly built villa of a successful businessman overlooking the coast."),
    GRASTSTANWAY("Graststan Way", "A country pub in a medium sized town."),
    LIMORE("Limore", "A country church"),
    CRUCOMBEWAY("Crucombe Way", "A bookmakers in open countryside."),
    VOUTHORP("Vouthorp", "A village"),
    DRIBORN("Driborn", "A country house"),
    ENOBROOK("Enobrook", "A science facility"),
    BRITHAMPPOND("Brithamppond End", "A hospital for the long term sick in remote countryside."),
    WECOTE("Wecote", "A small town"),
    GLELDHAM("Gleldham Hill", "A school atop a rise."),
    EDELDTHORP("Edeldthorp Drive", "A cul-de-sac on a modern housing development surrounded by seedy shops."),
    BOSBORN("Bosborn", "A country house"),
    FRIMORE("Frimore", "A boggy area of open countryside"),
    EVESTAN("Evestan", "A copse growing on the skyline"),
    KALDBURYWAY("Kaldbury Way", "A country pub in open countryside."),
    CHETON("Cheton", "A village postoffice"),
    AMOBURNWAY("Amoburn Way", "A country pub in the middle of a city."),
    HOUHOLMGAP("Houholm Gap", "A pass at the end of a narrow gorge in open countryside."),
    CRUCKFIELD("Cruckfield", "A village"),
    SHOUWICH("Shouwich", "A boronial hall"),
    KOUBROOKSTREET("Koubrook Street", "A layby on a long straight road between two cities in open countryside."),
    ANEDCOMBECHASE("Anedcombe Chase", "A semi detached villa in a private cul-de-sac in the suburbs of the city."),
    FRODTHWAITE("Frodthwaite", "A village in a forest."),
    SHUCKWICH("Shuckwich", "A small town."),
    ANOTHAMPSTAN("Anothampstan", "A copse growing on the skyline."),
    LUBURNPASS("Luburn Pass", "A motorway service station in open countryside."),
    GRAHOLMLAK("Graholm Lake", "A car park with an ice cream van in parkland."),
    SCHUCOMBE("Schucombe", "A bridge at the head of a deep river valley."),
    ILBURN("Ilburn", "A parish church."),
    TWIOCK("Twiock", "A country house."),
    CRUCKDON("Cruckdon", "A small mountain."),
    CRETON("Creton", "A forest."),
    LUHOLD("Luhold", "A small castle."),
    EDOHAMTYE("Edoham Tye", "A barn outside a small country town."),
    DRESWICH("Dreswich", "A country estate."),
    BREHOME("Brehome", "A church."),
    TWOBURNFORD("Twoburn Ford", "A lonely spot underneath overhanging willows beside the river in a rundown but, bustling part of town."),
    SWECKCOTEROAD("Sweckcote Road", "An apartment in a run down block in the middle of a city."),
    ALAHOLD("Alahold", "A small castle."),
    AMOCKHAMGATE("Amockham Gate", "The yard of a haulage company beside an ancient stone bridge."),
    STOGROVETYE("Stogrove Tye", "A secret government bunker outside a small country town."),
    DADALELAKE("Dadale Lake", "A spooky lake always covered by mist and buzzing insects in unspoilt countyside."),
    MUTHAMPDALE("Muthampdale", "A narrow valley."),
    ESEBORNMEADOW("Eseborn Meadow", "An unexceptional development of similar looking houses in a dormitory town c,lose to rolling countryside."), //50
    SWOUNTOCK("Swountock", "A small village."),
    BLOSTOW("Blostow Way", "A corner shop in the middle of a city."),
    GLONGBY("Glongby Corner", "A large out of town furniture store in open countryside."),
    ALANTHCOMBE("Alanthcombe Road", "The end house of a terrace of Victorian town houses in a medium sized town."),
    DOULDWICK("Douldwick", "A service station on a major road."),
    CRENTHMORE("Crenthmore Drive", "A cul-de-sac on a modern housing development in a rough area."),
    ROCKSTAN("Rockstan", "The site of an ancient battle."),
    SHISTAN("Shistan Corner", "A large out of town furniture store in the middle of the city."),
    GLUDTHORP("Gludthorp", "A small town."),
    CROUNTDALE("Crountdale", "A narrow valley."),
    WOUNGGROVE("Wounggrove", "A village based on a canal."),
    TROULDDALE("Troulddale Mount", "A steep hill in open country beloved by walkers surrounded by gentle hills."),
    SPOUON("Spouon Corner", "A chicken shed down a narrow gap between farm buildings in the middle of the city."),
    THUFIELD("Thufield Ford", "A lonely spot underneath overhanging willows beside the river in a sprawling urban area."),
    ACKIDALE("Ackidale Chase", "A gothic hunting lodge in open parkland."),
    RHYNSTBROOK("Rhynstbrook", "A science facility."),
    HOCOMBE("Hocombe", "A small west country harbour."),
    PLOUNGDALE("Ploungdale", "A modern housing development."),
    FREDALE("Fredale Ford", "A well kept cottage in a rundown but bustling part of town."),
    ATEBORN("Ateborn Castle", "The main residence of an aristocrat overlooking the coast."),
    ASSOSDALE("Assosdale", "A desolate beauty spot."),
    GLOLTHOLM("Gloltholm Mount", "A mansion dominating the skyline."),
    NAMORE("Namore Bridge", "A small village that has become industrialised down the coast from a seaside resort."),
    CRUNSTBORN("Crunstborn House", "A school converted from an old country house on its own private estate."),
    FONTHOLD("Fonthold Inn", "A sprawling roadside eating place in the middle of the city."),
    BRESTAN("Brestan", "A rocky outcrop."),
    INIDSTAN("Inidstan", "A grove of trees."),
    TRICKDON("Trickdon", "A parish church."),
    ENASTON("Enaston", "A village postoffice."),
    EDODON("Edodon", "A village built on a hill."),
    CHAPOND("Chapond Meadow", "A cemetery just off a farm road."),
    ISLERTHWAITE("Islerthwaite House", "A commercial building in a tiny village."),
    CLOBURN("Cloburn Castle", "An imposing heritage site that dominates the skyline on its own private estate."),
    BLOUWORTH("Blouworth", "A seaside village that was once an important port."),
    MOTHAMPCOMBE("Mothampcombe Pass", "A rural village on a trunk road tucked into the suburbs of the city."),
    AVEBURY("Avebury", "An ancient hill fort."),
    BLUTON("Bluton Bridge", "A small village house down the coast from a seaside resort."),
    WOUON("Wouon Drive", "A cul-de-sac on a modern housing development in a retirement village."),
    EROUDHOLD("Eroudhold", "A rocky outcrop."),
    SPACKBY("Spackby", "A village."),
    STOUOCK("Stouock Park", "A nineteen thirties semi in a leafy suburb of the city."),
    TIFIELD("Tifield", "A village."),
    BLURPOND("Blurpond Tye", "A barn outside a small country town."),
    GROTHTON("Grothton", "A parish church."),
    EROUTBY("Eroutby Cottage", "A farm workers ramshackle house in the middle of the city."),
    POBROOK("Pobrook", "An institute for the insane."),
    ABOUHOLM("Abouholm", "A village inside a glacial river valley with open water to the sea."),
    JUSTOW("Justow", "A coastal town."),
    GROUGROVE("Grougrove Gap", "A pass at the end of a narrow gorge in open countryside."),
    GAYWICK("Gaywick", "An old country house with farm buildings."),
    WHAHOLM("Whaholm Pass", "A pass at the end of a narrow gorge in wooded landscape."),
    ABOSTHWAITE("Abosthwaite Gate", "The yard of a haulage company on the outskirts of the city."),
    GOCKPOND("Gockpond", "A mill."),
    CRACOTE("Cracote", "A farm."),
    AVEPOND("Avepond", "A farm."),
    SLOTHAMPHOME("Slothamphome", " A country house."),
    ATEDON("Atedon", " A parish church."),
    TRIGHTHOLD("Trighthold", " A small castle."),
    DOUDFIELD("Doudfield Dyke", " A small iron bridge in marshy flat land.");

    private final String name;
    private final String description;
}
